### ISSUE TITLE
.gitignore file missing from template

### ISSUE THREAD

**Issue by etsuo** [etsuo/generator-hybrid#13]
0.0.1 doesn't copy .gitignore

```bash
events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-hybrid/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-hybrid/node_modules/mem-fs-editor/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-hybrid/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at null.<anonymous> (/usr/local/lib/node_modules/generator-hybrid/generators/app/index.js:256:25)
    at Array.forEach (native)
    at copyFiles (/usr/local/lib/node_modules/generator-hybrid/generators/app/index.js:253:17)
    at writing (/usr/local/lib/node_modules/generator-hybrid/generators/app/index.js:178:25)
    at /usr/local/lib/node_modules/generator-hybrid/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by etsuo** [comment]
See: https://github.com/yeoman/generator/issues/812

The way npm works, if it doesn't find a .npmignore file in the directory, it will rename .gitignore to .npmignore, so I added an empty .npmignore file in the app/templates directory.
